name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Repackage AWS CLI v2
        run: ./repackage-awscli
